<?php
namespace fw_Gunicorn\kernel\engine\applications\login;
use fw_Gunicorn\kernel\classes\abstracts\aLogin;


class Login extends aLogin{
    public function sessionStart()
    {
        parent::sessionStart(); // TODO: Change the autogenerated stub
    }

    function sync(){

    }

}